name: Issue To Pr

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  validate:
    name: Issue To Pr
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Parse Issue Body
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_token.yml

      - name: Parse Token
        id: parse-token
        run: node scripts/parseToken.mjs
        with:
          token: ${{ steps.issue-parser.outputs.jsonString }}

      - name: Checkout Branch
        run: git checkout -B ${{ steps.parse-token.outputs.prealpha-env }}

      - name: Add Token
        id: add-token
        run: node scripts/addToken.mjs
        with:
          token: ${{ steps.parse-token.outputs.issueparser_symbol }}

      # - name: Submit New Token
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: scroll.tokenlist.json
      #     message: add ${{ steps.issue-parser.outputs.issueparser_symbol }}
      #     new_branch: ${{ steps.issue-parser.outputs.issueparser_symbol }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[New Token] name: ${{ steps.issue-parser.outputs.issueparser_name }}'
          commit-message: add ${{ steps.issue-parser.outputs.issueparser_symbol }}
          base: ${{ steps.add-token.outputs.prealpha-env }}
          branch: new-token/${{ steps.issue-parser.outputs.issueparser_symbol }}
          delete-branch: true
          add-paths: scroll.tokenlist.json
          labels: |
            new token
            need to review
