name: Issue To Pr

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  issue-to-pr:
    name: Issue To Pr
    runs-on: ubuntu-latest
    outputs:
      branch-name: new-token/${{ steps.issue-parser.outputs.issueparser_symbol }}
      pr-number: ${{ steps.create-pr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Parse Issue Body
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_token.yml

      - name: Parse Token
        id: parse-token
        run: node scripts/parseToken.mjs
        env:
          RESOLVED_TOKEN_STR: ${{ steps.issue-parser.outputs.jsonString }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.parse-token.outputs.prealpha-env }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Add Token
        id: add-token
        run: node scripts/addToken.mjs
        env:
          NEW_TOKEN: ${{ steps.parse-token.outputs.new-token }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[New Token] name: ${{ steps.issue-parser.outputs.issueparser_name }}'
          body: 'Refer Issue: #${{ github.event.issue.number }}'
          commit-message: add ${{ steps.issue-parser.outputs.issueparser_symbol }}
          base: ${{ steps.parse-token.outputs.prealpha-env }}
          branch: new-token/${{ steps.issue-parser.outputs.issueparser_symbol }}
          delete-branch: true
          add-paths: scroll.tokenlist.json
          labels: |
            new token
            need to review

  validate:
    name: Validate Token List
    runs-on: ubuntu-latest
    needs: issue-to-pr
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{needs.issue-to-pr.outputs.branch-name}}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Validate Token List
        id: validate-token-list
        run: node scripts/validateJson.mjs

      - name: Show Token List
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :tada: [Click here](https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/scroll-tech/token-list/${{ github.head_ref }}/scroll.tokenlist.json) to preview token list
          comment_tag: tokenListUrl
          pr_number: ${{needs.issue-to-pr.outputs.pr-number}}

      - name: Mark Issue Error
        if: steps.validate-token-list.outcome == 'failure'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'validation failure'
