name: Issue To Pr

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: staging

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Parse Issue Body
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_token.yml

      - name: Export New Token
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > new_token.json

      - name: Checkout New Branch
        run: git checkout -B ${{ steps.issue-parser.outputs.issueparser_symbol }}

      - name: Add New Token
        run: node scripts/addToken.mjs

      - name: Submit New Token
        uses: EndBug/add-and-commit@v9
        with:
          add: scroll.tokenlist.json
          message: add ${{ steps.issue-parser.outputs.issueparser_symbol }}
          new_branch: ${{ steps.issue-parser.outputs.issueparser_symbol }}
