name: Validate TokenList

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run validate script
        run: node scripts/validateJson.mjs

  show:
    name: online address
    needs: validate
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            You can view token list https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/scroll-tech/token-list/${{ github.head_ref }}/scroll.tokenlist.json
