name: Validate TokenList

on:
  push:
    paths:
      - scroll.tokenlist.json
  pull_request:
    paths:
      - scroll.tokenlist.json

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run validate script
        run: node scripts/validateJson.mjs
